<?php
/**
 * @var \Ajith\Test\Block\Display $block
 */
echo $block->sayHello();?>
<h3>AJith</h3>


    <script>
    let scene, camera, renderer,cube;
    let ADD=0.1;
    
    
    let init= function(){
        scene = new THREE.Scene();
        scene.background = new THREE.Color(0xababab);
        camera = new THREE.PerspectiveCamera(30, window.innerWidth/window.innerHeight,1,1000);
        camera.position.z=5;
      
        // createCube();

        renderer=new THREE.WebGLRenderer();
        renderer.setSize(window.innerWidth, window.innerHeight);
        document.body.appendChild(renderer.domElement);
    };
    
    let mainLoop = function(){
    
        renderer.render(scene,camera);
        requestAnimationFrame(mainLoop);

    };

    let reload = function(){
            window.addEventListener('resize',() => {
                renderer.setSize(window.innerWidth,window.innerHeight);
                camera.aspect = window.innerWidth / window.innerHeight;
                camera.updateProjectMatrix();
            })
        };

    init();
    reload();
    mainLoop();
</script>